# Generated by Django 3.1.5 on 2021-01-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='enderecos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=9)),
                ('logradouro', models.TextField()),
                ('numero', models.TextField()),
                ('complemento', models.TextField()),
                ('bairro', models.TextField()),
                ('cidade', models.TextField()),
                ('uf', models.CharField(max_length=2)),
                ('descricao', models.TextField()),
            ],
        ),
    ]
